user root;
worker_processes auto;
events { worker_connections 1024; }
http {
    include /etc/nginx/mime.types;

    server {
        listen 80;

        location / {
            root /usr/share/nginx/html;
            index index.html;
        }

        location /api/ {
            proxy_pass http://scanner:5000/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
